version: '3.1'

services:

  db:
    build: ./mysql
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/persisted_data:/bitnami/mysql/data
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
    networks:
      wp-bridge:

  wordpress:
    build: ./wordpress-baseline
    image: ${DOCKER_REGISTRY}/bu-wordpress-baseline
    container_name: wordpress
    restart: always
    hostname: dev.kualitest.research.bu.edu
    ports:
      - '443:443'
      - '80:80'
    environment:
      SERVER_NAME: dev.kualitest.research.bu.edu
      SP_ENTITY_ID: https://*.kualitest.research.bu.edu/shibboleth
      IDP_ENTITY_ID: https://shib-test.bu.edu/idp/shibboleth
      SHIB_SP_KEY_FILE: sp-key.pem
      SHIB_SP_CERT_FILE: sp-cert.pem
      TZ: America/New_York
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DEBUG: true
    volumes:
      - ./wordpress-baseline/sandbox/:/var/www/html/
      - ./wordpress-baseline/sp-key.pem:/etc/shibboleth/sp-key.pem
      - ./wordpress-baseline/sp-cert.pem:/etc/shibboleth/sp-cert.pem
      - ./wordpress-baseline/logs-apache:/var/log/apache2
      - ./wordpress-baseline/logs-shib:/var/log/shibboleth
    # secrets:
    #   - wp-sp-key
    networks:
      wp-bridge:

networks:
  wp-bridge:
    driver: bridge

# secrets:
#   wp-sp-shib:
#     name: ${SECRETS_MANAGER_SHIB_SECRET}
#     x-aws-keys:
#       - wp-sp-key
#       - wp-sp-cert
#     external: true

    # /run/secrets/wp-sp-shib/wp-sp-key
