version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
    networks:
      wp-bridge:

  wordpress:
    env_file:
      - .env
      - .env.shibless
    depends_on:
      - db
    build: ./wordpress-baseline
    image: ${DOCKER_REGISTRY}/bu-wordpress-baseline
    container_name: wordpress
    restart: always
    hostname: dev.kualitest.research.bu.edu
    ports:
      - '443:443'
      - '80:80'
    environment:
      SERVER_NAME: dev.kualitest.research.bu.edu
      TZ: America/New_York
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true
      WP_CLI_ALLOW_ROOT: true
    volumes:
      - ./wordpress-baseline/sandbox/:/var/www/html/
      - ./wordpress-baseline/logs-apache:/var/log/apache2
    networks:
      wp-bridge:

networks:
  wp-bridge:
    driver: bridge
volumes:
  db_data: {}
