version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
    networks:
      wp-bridge:

  wordpress:
    depends_on:
      - db
    build: ./wordpress-baseline
    image: ${DOCKER_REGISTRY}/bu-wordpress-baseline
    container_name: wordpress
    restart: always
    hostname: dev.kualitest.research.bu.edu
    ports:
      - '443:443'
      - '80:80'
    environment:
      SERVER_NAME: dev.kualitest.research.bu.edu
      HTTP_HOST: dev.kualitest.research.bu.edu
      SP_ENTITY_ID: https://*.kualitest.research.bu.edu/shibboleth
      IDP_ENTITY_ID: https://${SHIB_DOMAIN}/idp/shibboleth
      SHIB_IDP_LOGOUT: https://${SHIB_DOMAIN}/idp/logout.jsp
      SHIB_SP_KEY: ${SHIB_SP_KEY}
      SHIB_SP_CERT: ${SHIB_SP_CERT}
      TZ: America/New_York
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true
      WP_CLI_ALLOW_ROOT: true
    volumes:
      - ./wordpress-baseline/sandbox/:/var/www/html/
      # - ./wordpress-baseline/sp-key.pem:/etc/shibboleth/sp-key.pem
      # - ./wordpress-baseline/sp-cert.pem:/etc/shibboleth/sp-cert.pem
      - ./wordpress-baseline/logs-apache:/var/log/apache2
      - ./wordpress-baseline/logs-shib:/var/log/shibboleth
    # secrets:
    #   - wp-sp-key
    networks:
      wp-bridge:

networks:
  wp-bridge:
    driver: bridge
volumes:
  db_data: {}

# secrets:
#   wp-sp-shib:
#     name: ${SECRETS_MANAGER_SHIB_SECRET}
#     x-aws-keys:
#       - wp-sp-key
#       - wp-sp-cert
#     external: true

    # /run/secrets/wp-sp-shib/wp-sp-key
