version: '3.9'

services:

  wordpress:
    image: bu-wordpress-build
    build: 
      context: ./wordpress-build      
      args:
        GIT_USER: whennemuth
        GIT_TOKEN_FILE: /usr/local/bin/pat
        MANIFEST_INI_FILE: wp-manifests/devl/jaydub-bulb.ini
        REPOS: 'responsive-framework-2-x, bu-cms, bu-sustainability, query-monitor'
    environment:
      S3PROXY_HOST: s3proxy.kualitest.research.bu.edu
      FORWARDED_FOR_HOST: jaydub-bulb.cms-devl.bu.edu
      DB_NAME: wb_db
      DB_USER: root
      DB_HOST: db
      DB_CHARSET: utf8
      WORDPRESS_CONFIG_EXTRA: |
        define( 'DB_PASSWORD', '${DB_PASSWORD}');
