version: '3.9'

services:

  db:
    extends:
      file: compose-baseline.yml
      service: db

  wordpress:
    extends:
      file: compose-baseline.yml
      service: wordpress
    image: ${DOCKER_REGISTRY}/bu-wordpress-build 
    build: 
      context: ./wordpress-build      
      args:
        BASE_IMAGE: ${DOCKER_REGISTRY}/bu-wordpress-baseline
        GIT_USER: ${GIT_USER}
        GIT_PAT: ${GIT_PAT}
        MANIFEST_INI_FILE: ${MANIFEST_INI_FILE}
        REPOS: ${REPOS}
    environment:
      S3PROXY_HOST: https://s3proxy.kualitest.research.bu.edu/
      FORWARDED_FOR_HOST: jaydub-bulb.cms-devl.bu.edu
      WORDPRESS_CONFIG_EXTRA: |
        define( 'S3_UPLOADS_BUCKET', '${S3_UPLOADS_BUCKET}');
        define( 'S3_UPLOADS_REGION', '${S3_UPLOADS_REGION}');
        define( 'S3_UPLOADS_KEY', '${S3_UPLOADS_KEY}');
        define( 'S3_UPLOADS_SECRET', '${S3_UPLOADS_SECRET}');
        define( 'ACCESS_RULES_TABLE', '${ACCESS_RULES_TABLE}');

networks:
  wp-bridge:
    driver: bridge