# docker-compose.yml
#
# This Docker Compose file extends the baseline configuration defined in compose-baseline.yml to set up a local development environment for our application.
# It includes additional configurations for the `db` and `wordpress` services, and defines a custom WordPress image that is built from our local WordPress build context.
#
# Services:
# - db: Extends the `db` service from compose-baseline.yml. No additional configurations are added in this file.
# - wordpress: Extends the `wordpress` service from compose-baseline.yml. Adds a custom image and build context, and sets additional environment variables for local development.
#
# Networks:
# - wp-bridge: A network that allows our services to communicate with each other. This is the same network defined in compose-baseline.yml.
#
# Volumes:
# - db_data: A volume that persists our database data across container restarts. This is the same volume defined in compose-baseline.yml.
#
# Note: This file uses environment variables for certain settings, such as the Docker registry and Git credentials. These should be set in your environment before running Docker Compose.

version: '3.9'

services:

  db:
    extends:
      file: compose-baseline.yml
      service: db

  wordpress:
    extends:
      file: compose-baseline.yml
      service: wordpress
    image: ${DOCKER_REGISTRY}/bu-wordpress-build 
    build: 
      context: ./wordpress-build      
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        GIT_USER: ${GIT_USER}
        GIT_PAT: ${GIT_PAT}
        MANIFEST_INI_FILE: ${MANIFEST_INI_FILE}
        REPOS: ${REPOS}
    environment:
      S3PROXY_HOST: http://s3proxy:8080/
      FORWARDED_FOR_HOST: jaydub-bulb.cms-devl.bu.edu
      MULTISITE: true
      WORDPRESS_CONFIG_EXTRA: |
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define( 'S3_UPLOADS_BUCKET', '${S3_UPLOADS_BUCKET}');
        define( 'S3_UPLOADS_REGION', '${S3_UPLOADS_REGION}');
        define( 'S3_UPLOADS_SECRET', '${S3_UPLOADS_SECRET_ACCESS_KEY}');
        define( 'S3_UPLOADS_KEY', '${S3_UPLOADS_ACCESS_KEY_ID}');
        define( 'ACCESS_RULES_TABLE', '${ACCESS_RULES_TABLE}');
        define( 'S3_UPLOADS_OBJECT_ACL', null);
        define( 'S3_UPLOADS_AUTOENABLE', true );
        define( 'S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL', true);
        define( 'BU_INCLUDES_PATH', '/var/www/html/bu-includes' );

networks:
  wp-bridge:
    driver: bridge
volumes:
  db_data: {}
