version: '3.9'

services:

  wordpress:
    image: bu-wordpress-build
    build: 
      context: ./wordpress-build      
      args:
        GIT_USER: whennemuth
        GIT_TOKEN_FILE: /usr/local/bin/pat
        MANIFEST_INI_FILE: wp-manifests/devl/jaydub-bulb.ini
        REPOS: 'responsive-framework-2-x, bu-cms, bu-sustainability, query-monitor'
    environment:
      S3PROXY_HOST: s3proxy.kualitest.research.bu.edu
      FORWARDED_FOR_HOST: jaydub-bulb.cms-devl.bu.edu
      WORDPRESS_CONFIG_EXTRA: |
        define( 'S3_UPLOADS_BUCKET', '${S3_UPLOADS_BUCKET}');
        define( 'S3_UPLOADS_REGION', '${S3_UPLOADS_REGION}');
        define( 'S3_UPLOADS_KEY', '${S3_UPLOADS_KEY}');
        define( 'S3_UPLOADS_SECRET', '${S3_UPLOADS_SECRET}');
        define( 'ACCESS_RULES_TABLE', '${ACCESS_RULES_TABLE}');
