version: '3.9'

services:

  wordpress:
    image: bu-wordpress-build
    build: 
      context: ./wordpress-build      
      args:
        GIT_USER: whennemuth
        GIT_TOKEN_FILE: /usr/local/bin/pat
        MANIFEST_INI_FILE: wp-manifests/devl/jaydub-bulb.ini
        SITES: 'responsive-framework-2-x, bu-cms, bu-sustainability, query-monitor'
    environment:
      S3PROXY_HOST: s3proxy.kualitest.research.bu.edu
      # S3PROXY_HOST=dualstack.internal-s3pro-s3pro-1ksb20endt9vw-1289646701.us-east-1.elb.amazonaws.com.
      FORWARDED_FOR_HOST: jaydub-bulb.cms-devl.bu.edu
      # Overrided the shibboleth credentials with empty strings to skip setup of SP and authentication with the IDP.
      # SHIB_SP_KEY: ""
      # SHIB_SP_CERT: ""
